//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.07 at 10:15:23 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://my.shop.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.shop.my;
